#page title
page_title                                : Copeo Timesheets                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/copeo-timesheet-submission/id1566616378?platform=iphone                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=copeo.timesheets.employee                                          # Enter Google Play Store URL.
presskit_download_link                    : https://www.copeo.app # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                            # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Copeo <br> Timesheets                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Employer time approval and Employee time submission apps for small businesses, contractors and NGOs. <br> <b> <i>Simple.    Precise.    Super Affordable. </i></b> <br/> <br/> Download Employee Apps

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Medha Karri                                
your_link                                 :                   
your_city                                 : Wright State University, Dayton, Ohio                                
email_address                             : medhachaitanya@outlook.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Employees submit time to manager
    description                           : No discrepancies or wrong calculations involved 
    fontawesome_icon_name                 : mobile
    
  - title                                 : Employee Clock In and Clock Out
    description                           : Automatically calculate the total hours worked for each day.
    fontawesome_icon_name                 : clock

  - title                                 : Week Totals
    description                           : See the total worked hours for the whole week along with the regular hours and the over-time hours.
    fontawesome_icon_name                 : calendar-week

  - title                                 : Pay Info
    description                           : View earning per work period
    fontawesome_icon_name                 : money-check-alt
  
  - title                                 : Simple User Interface
    description                           : Submit & see timesheets with effortless UI  
    fontawesome_icon_name                 : check-circle
    
  - title                                 : Timesheets Mode | Daily, Weekly Mode
    description                           : Submit time daily or Submit weekly.  
    fontawesome_icon_name                 : check-circle



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

theme: jekyll-theme-cayman